version: '3'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarqube
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonarqube
    networks:
      - sonarqube-network
    depends_on:
      - sonarqube-db

  sonarqube-db:
    image: postgres:alpine
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_DB=sonarqube
    networks:
      - sonarqube-network
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data

networks:
  sonarqube-network:
    driver: bridge

volumes:
  sonarqube-db-data:
    driver: local

